export const LIST_STARTPOINTS_REQUEST = 'LIST_STARTPOINTS_REQUEST';
export const LIST_STARTPOINTS_SUCCESS = 'LIST_STARTPOINTS_SUCCESS';
export const LIST_STARTPOINTS_FAILURE = 'LIST_STARTPOINTS_FAILURE';